apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/techdocs-ref: url:PUT_YOUR_OPENAPI_RAW_URL_HERE
  description: This is the Astra API Swagger documentation.This server is based on
    the OpenAPI 3.0 specification.
  name: astra-3.n---openapi-3.0
spec:
  definition:
    components:
      schemas:
        Bundle:
          properties:
            entry:
              items:
                $ref: '#/components/schemas/resource'
              type: array
            identifier:
              properties:
                type:
                  properties:
                    text:
                      enum:
                      - Disinfection Cycle
                      - Wild Cycle
                      - HLD Replaced
                      - Test Strip Bottle Enrolled
                      - Water Filter Replaced
                      - Air Filter Replaced
                      - Firmware Replaced
                      - Annual Calibration and Conductivity Probe Replaced
                      example: Astra Event
                      type: string
                  type: object
              type: object
            resourceType:
              example: Bundle
              type: string
            type:
              example: collection
              type: string
          type: object
        Device:
          properties:
            extension:
              items:
                $ref: '#/components/schemas/Extension'
              type: array
            resourceType:
              example: Astra Device
              type: string
          type: object
        Extension:
          properties:
            url:
              enum:
              - Daily Cycle Count
              - Lifetime Cycle Count
              example: Cycle Count
              type: string
            valueInteger:
              example: 0
              type: integer
          type: object
        resource:
          properties:
            resourceType:
              enum:
              - Procedure
              - Substance
              - Practitioner
              - Organization
              - Device
              - DeviceDefinition
              - Observation
              example: Procedure
              type: string
            status:
              enum:
              - completed
              - not done
              example: completed
              type: string
          type: object
      securitySchemes:
        BasicAuth:
          scheme: basic
          type: http
    externalDocs:
      description: Find out more about Swagger
      url: http://swagger.io
    info:
      description: This is the Astra API Swagger documentation.This server is based
        on the OpenAPI 3.0 specification.
      termsOfService: http://swagger.io/terms/
      title: Astra 3.N - OpenAPI 3.0
      version: 1.0.0
    openapi: 3.0.0
    paths:
      /airfilterreplaced:
        get:
          description: Get the information for the last air filter replaced procedure
            performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get air filter replaced data
          tags:
          - Astra Data
      /annualcalibrationconductivityprobereplaced:
        get:
          description: Get the information for the last annual calibration and conductivity
            probe replaced procedure performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get annual calibration and conductivity probe replaced data
          tags:
          - Astra Data
      /astrastatus:
        get:
          description: Get the status information for the last astra device cycle
            procedure performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Device'
              description: Sucessful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get astra device status data
          tags:
          - Astra Data
      /cyclecount:
        get:
          description: Get the information for the daily cycle count and lifetime
            cycle count on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Device'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get cycle count data
          tags:
          - Astra Data
      /disinfectioncycle:
        get:
          description: Get the information for the last disinfection cycle procedure
            performed on astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get disinfection cycle data
          tags:
          - Astra Data
      /firmwarereplaced:
        get:
          description: Get the information for the last firmware replaced procedure
            performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get firmware replaced data
          tags:
          - Astra Data
      /hldreplacedCycle:
        get:
          description: Get the information for the last HLD Replaced procedure performed
            on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get HLD replaced data
          tags:
          - Astra Data
      /teststripbottleenrolled:
        get:
          description: Get the information for the last test strip bottle enrolled
            procedure performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get test strip bottle enrolled data
          tags:
          - Astra Data
      /waterfilterreplaced:
        get:
          description: Get the information for the last water filter replaced procedure
            performed on the astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get water filter replaced data
          tags:
          - Astra Data
      /wildcycle:
        get:
          description: Get the information for the last wild cycle procedure performed
            on astra device.
          responses:
            '200':
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Bundle'
              description: Successful response
            '401':
              description: Unauthorized
            '404':
              description: Resource not found
          summary: Get wild cycle data
          tags:
          - Astra Data
    security:
    - BasicAuth: []
    servers:
    - description: Base URL for API requests
      url: http://{baseUrl}
      variables:
        baseUrl:
          default: 127.0.0.1:443
          description: Your local Astra API server IP address
    tags:
    - description: Information about procedure/activity carried on the astra device.
      name: Astra Data
  lifecycle: production
  owner: your-team
  type: openapi
