apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: astra-api
  description: Astra API for device cycle and status information.
  tags:
    - rest
    - swagger
    - astra
spec:
  type: openapi
  lifecycle: production
  owner: astra-team
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Astra 3.N - OpenAPI 3.0
        description: >-
          This is the Astra API Swagger documentation. This server is based on the
          OpenAPI 3.0 specification.
        termsOfService: http://swagger.io/terms/
        version: 1.0.0
      servers:
        - url: http://127.0.0.1:443
          description: Local Astra API Server
      paths:
        /cyclecount:
          get:
            summary: Get cycle count data
            description: >-
              Get the information for the daily cycle count and lifetime cycle count
              on the Astra device.
            responses:
              '200':
                description: Successful response
      security:
        - BasicAuth: []
      components:
        securitySchemes:
          BasicAuth:
            type: http
            scheme: basic
